[PHP]
memory_limit = 512M
max_execution_time = 300
max_input_time = 300
post_max_size = 20M
upload_max_filesize = 20M
max_file_uploads = 20
default_charset = "UTF-8"

display_errors = Off
display_startup_errors = Off
log_errors = On
error_reporting = E_ALL & ~E_DEPRECATED & ~E_STRICT
error_log = /var/www/v2board/storage/logs/php-error.log

[Date]
date.timezone = Asia/Shanghai

[opcache]
opcache.enable = 1
opcache.enable_cli = 0
opcache.memory_consumption = 128
opcache.max_accelerated_files = 10000
opcache.validate_timestamps = 0

[curl]
curl.cainfo = /etc/ssl/certs/ca-certificates.crt

[openssl]
openssl.cafile = /etc/ssl/certs/ca-certificates.crt
